const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const data=require('../lib/data.cjs'),{query}=require('../lib/query.cjs');
function prefs(){const c=vm.createContext({window:{MetricsData:data}});vm.runInContext(fs.readFileSync('public/preferences.js','utf8'),c);return c.window.MetricsPreferences;}
function sample(){const base=data.load(),a='SPRINT-A 28/09/2026 a 02/10/2026 (GSAS)',b='SPRINT-B 30/09/2026 a 06/10/2026 (GSAS)',card={...base.items[0],type:'História',project:'A',sprint:a,start:'2026-09-28',end:'2026-10-02',owner:'Ana',planned:true};return {...base,items:[{...card,id:1,status:'10-Pronto para homologação',points:3},{...card,id:2,status:'11-Concluído',points:5},{...card,id:3,status:'01-Novo',points:null,planned:null,owner:'Bia'},{...card,id:4,status:'10-Pronto para homologação',points:2,planned:false},{...card,id:5,type:'Ordem de Serviço',points:null},{...card,id:6,type:'Ordem de Serviço',sprint:b,start:'2026-09-30',end:'2026-10-06'}],hours:[{...base.hours[0],id:1,project:'A',owner:'Ana',date:'2026-09-30',hours:8},{...base.hours[0],id:2,project:'A',owner:'Ana',date:'2026-10-06',hours:4}],cycle:[],lead:[],rework:[],throughput:[],aging:[]};}
test('SP realizado usa pronto para homologação; entrega usa só os planejados prontos',()=>{const r=data.summary(sample());assert.equal(r.stats.readyPoints,5);assert.equal(r.stats.donePoints,5);assert.equal(r.stats.readyDelivery,37.5);assert.equal(r.projectStats[0].progress,50);});
test('total da lista e planejamento ausente respeitam busca, categoria e desenvolvedor',()=>{const base=sample();const r=query(base,data,new URLSearchParams({view:'sprint',owner:'Ana'}));assert.equal(r.items.total,3);assert.equal(r.tableSummary.points,10);const missing=query(base,data,new URLSearchParams({view:'sprint',tab:'unknownPlan'}));assert.equal(missing.items.total,1);assert.equal(missing.items.rows[0].id,3);assert.equal(missing.tableSummary.missingPoints,1);assert.equal(query(base,data,new URLSearchParams({view:'sprint',tab:'unplanned'})).items.total,1);});
test('preferências de sprint e OS persistem; períodos sobrepostos contam cada hora e dia uma vez',()=>{const p=prefs(),base=sample(),values=new Map(),store={setItem:(k,v)=>values.set(k,v),getItem:k=>values.get(k)};const selected=[base.items[0].sprint,base.items.at(-1).sprint];p.save(store,{projects:null,owners:null,sprints:selected,orders:['5']});const restored=p.read(store),scoped=p.scope(base,restored);assert.equal(restored.sprints.length,2);assert.deepEqual(scoped.items.filter(x=>x.type==='Ordem de Serviço').map(x=>x.id),[5]);const r=query(scoped,data,new URLSearchParams({view:'hours'}));assert.equal(r.stats.hours,12);assert.equal(r.capacity.days,7);assert.equal(r.stats.expectedHours,56);assert.equal(p.scope(base,{...restored,sprints:[]}).items.length,0);assert.equal(p.scope(base,{...restored,sprints:[]}).hours.length,0);});
test('todos os menus de cards persistem multiseleção de status e tipo',()=>{const c=vm.createContext({window:{}});vm.runInContext(fs.readFileSync('public/view-state.js','utf8'),c);for(const view of ['sprint','dashboard','compare','evolution','os']){const r=c.window.MetricsViewState.clean(view,{filters:{status:['A','B'],type:['História','Bug']}});assert.equal(r.filters.status.length,2);assert.equal(r.filters.type.length,2);}});
test('esforço compara intervalos sem duplicar o total e reconcilia gráficos',()=>{const base=sample(),q=new URLSearchParams({view:'effort'});q.append('sprint',base.items[0].sprint);q.append('sprint',base.items.at(-1).sprint);const r=query(base,data,q);assert.equal(r.stats.hours,12);assert.deepEqual(r.effortComparisons.map(x=>x.hours),[8,12]);assert.equal(data.sum(r.charts.projectHours,'value'),r.stats.hours);assert.equal(data.sum(r.charts.activityHours,'value'),r.stats.hours);});
