const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const data=require('../lib/data.cjs'),{query}=require('../lib/query.cjs');
const storage=()=>{const values=new Map();return {getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)}};
function views(){const context=vm.createContext({window:{}});vm.runInContext(fs.readFileSync('public/view-state.js','utf8'),context);return context.window.MetricsViewState;}
test('filtros por tela sobrevivem a recarga e não se propagam a outras telas',()=>{const state=views(),store=storage();state.save(store,{sprint:{filters:{project:'SIPES',status:['01-Novo','11-Concluído']},search:'cadastro',tab:'planned'},hours:{filters:{owner:'Pessoa A',from:'2026-09-01',to:'2026-09-30'}}});const reopened=views().read(store);assert.equal(reopened.sprint.filters.project,'SIPES');assert.equal(reopened.sprint.filters.status.length,2);assert.equal(reopened.sprint.tab,'planned');assert.equal(reopened.sprint.search,'cadastro');assert.equal(reopened.hours.filters.owner,'Pessoa A');assert.equal(reopened.hours.filters.project,undefined);assert.equal(reopened.hours.filters.status,undefined);});
test('seleção manual vazia se mantém vazia, sem reativar gráficos automáticos',()=>{const state=views(),store=storage();state.save(store,{compare:{compareSprints:[]},evolution:{evolutionProjects:[]}});const value=state.read(store);assert.equal(value.compare.compareSprints.length,0);assert.equal(value.evolution.evolutionProjects.length,0);const base=data.load();assert.equal(query(base,data,new URLSearchParams({view:'compare',compareMode:'manual'})).comparisons.length,0);assert.equal(query(base,data,new URLSearchParams({view:'evolution',evolutionMode:'manual'})).evolution.length,0);});
test('base nova remove só os filtros indisponíveis, mantendo os demais',()=>{const state=views(),options={projects:['SIPES'],statuses:['11-Concluído'],types:[],sprints:[],squads:[],teams:[],owners:[],activities:[]};const r=state.reconcile('sprint',{filters:{project:'SIPES',status:['01-Novo','11-Concluído'],sprint:'REMOVIDA'}},options);assert.equal(r.changed,true);assert.equal(r.value.filters.project,'SIPES');assert.deepEqual(Array.from(r.value.filters.status),['11-Concluído']);assert.equal(r.value.filters.sprint,undefined);});
test('armazenamento bloqueado ou corrompido não impede leitura do sistema',()=>{const state=views();assert.equal(Object.keys(state.read({getItem(){throw Error('blocked')}})).length,0);assert.equal(state.save({setItem(){throw Error('full')}},{}),false);assert.equal(Object.keys(state.read({getItem:()=>'{invalid'})).length,0);const context=vm.createContext({window:{}});vm.runInContext(fs.readFileSync('public/preferences.js','utf8'),context);const p=context.window.MetricsPreferences.read({getItem:()=>JSON.stringify({demo:false,projects:['SIPES']}),setItem(){throw Error('full')}});assert.deepEqual(Array.from(p.projects),['SIPES']);assert.equal(p.demo,false);});
test('métricas agregadas não usam totais do squad quando colaboradores estão restritos',()=>{const r=query(data.load(),data,new URLSearchParams({view:'dashboard',ownerScope:'1'}));assert.equal(r.stats.cycle,null);assert.equal(r.stats.lead,null);assert.equal(r.stats.rework,null);assert.equal(r.stats.throughput,null);});
test('exportação respeita categoria selecionada e projetos do gráfico',()=>{const base=data.load(),sprint='SPRINT-33 28/09/2026 a 09/10/2026 (GSAS)',r=query(base,data,new URLSearchParams({view:'sprint',sprint,tab:'planned'})),csv=query(base,data,new URLSearchParams({action:'export',view:'cards',sprint,tab:'planned'}));assert.equal(csv.split('\r\n').length-1,r.items.total);assert.ok(csv.includes('"owner"'));const subset=query(base,data,new URLSearchParams({action:'export',view:'cards',exportProject:'SIPES'}));assert.equal(subset.split('\r\n').length-1,data.summary(base,{project:'SIPES'}).items.length);});
test('datas inexistentes e intervalos invertidos são rejeitados',()=>{for(const values of [{from:'2026-02-30'},{from:'2026-13-01'},{from:'2026-09-30',to:'2026-09-01'}])assert.throws(()=>data.queryFilters(new URLSearchParams(values)));assert.equal(data.queryFilters(new URLSearchParams({from:'2024-02-29'})).from,'2024-02-29');});
test('horas esperadas usam o período do projeto selecionado',()=>{const base=data.load(),sample={...base,hours:[{...base.hours[0],id:1,project:'A',owner:'Pessoa A',date:'2026-09-28',hours:8},{...base.hours[0],id:2,project:'A',owner:'Pessoa A',date:'2026-09-29',hours:8},{...base.hours[0],id:3,project:'B',owner:'Pessoa B',date:'2025-01-01',hours:1}]};const r=query(sample,data,new URLSearchParams({view:'hours',project:'A'}));assert.equal(r.capacity.days,2);assert.equal(r.stats.expectedHours,16);assert.equal(r.stats.hoursDifference,0);});
test('detalhe escolhe a ocorrência de uma das sprints multisselecionadas',()=>{const base=data.load(),sample={...base,items:[{...base.items[0],id:123,sprint:'A',start:'2026-09-01'},{...base.items[0],id:123,sprint:'B',start:'2026-10-01'}]},params=new URLSearchParams({action:'item',id:'123'});params.append('sprint','A');params.append('sprint','C');assert.equal(query(sample,data,params).item.sprint,'A');});
test('arquivo incompleto e contagens inconsistentes são rejeitados antes da substituição',()=>{const raw={schemaVersion:1,metadata:{counts:{items:1,hours:1}},items:[Array(12).fill(null)],hours:[Array(12).fill(null)],aging:[],cycle:[],lead:[],throughput:[],rework:[]};assert.equal(data.validate(raw),raw);assert.throws(()=>data.validate({...raw,hours:undefined}));assert.throws(()=>data.validate({...raw,metadata:{counts:{items:99,hours:1}}}));});
test('preferência de colaboradores não inclui cards sem responsável nem seleção vazia',()=>{const context=vm.createContext({window:{}});vm.runInContext(fs.readFileSync('public/preferences.js','utf8'),context);const base=data.load(),owner=base.items.find(x=>x.owner).owner,p={projects:null,owners:[owner],osLinks:{}};const scoped=context.window.MetricsPreferences.scope(base,p);assert.ok(scoped.items.length);assert.ok(scoped.items.every(x=>x.owner===owner));assert.equal(context.window.MetricsPreferences.scope(base,{...p,owners:[]}).items.length,0);});
function appHarness(){const nodes=new Map(),events={},store=storage();const node=key=>{if(!nodes.has(key))nodes.set(key,{textContent:'',innerHTML:'',hidden:false,open:false,addEventListener(){}});return nodes.get(key);};let failure=false,invalid=false;const root='.vercel/output/static',context=vm.createContext({URLSearchParams,Intl,Date,Set,Map,Blob,URL,location:{hash:'#dashboard'},document:{querySelector:node,addEventListener(){}},fetch:async()=>{if(failure)throw Error('Falha de conexão');return {ok:true,json:async()=>invalid?{schemaVersion:1}:JSON.parse(fs.readFileSync(root+'/data/snapshot.json','utf8'))};},setTimeout(){},clearTimeout(){},setInterval(){}});context.window=context;context.localStorage=store;context.addEventListener=(k,fn)=>events[k]=fn;for(const file of ['engine.js','query.js','preferences.js','mock-data.js','view-state.js','app.js'])vm.runInContext(fs.readFileSync(root+'/'+file,'utf8'),context,{filename:file});return {context,nodes,node,events,store,fail:()=>failure=true,invalid:()=>invalid=true};}
test('falha de atualização e arquivo inválido preservam a última base válida',async()=>{for(const condition of ['fail','invalid']){const app=appHarness();await new Promise(resolve=>setImmediate(resolve));const initial=await vm.runInContext('getDataset()',app.context);app[condition]();await assert.rejects(vm.runInContext('getDataset(true)',app.context));assert.equal(await vm.runInContext('getDataset()',app.context),initial);assert.equal(app.node('#side-source').textContent,'5.917 registros na base');}});
test('navegação e recarga recuperam filtros por tela; limpar restaura os gráficos automáticos',async()=>{const app=appHarness();await new Promise(resolve=>setImmediate(resolve));vm.runInContext("filters={project:'SIPES'};rememberView();location.hash='#hours'",app.context);app.events.hashchange();await new Promise(resolve=>setImmediate(resolve));assert.equal(vm.runInContext('filters.project',app.context),undefined);vm.runInContext("filters={from:'2026-09-01',to:'2026-09-30'};rememberView();location.hash='#dashboard'",app.context);app.events.hashchange();await new Promise(resolve=>setImmediate(resolve));assert.equal(vm.runInContext('filters.project',app.context),'SIPES');const saved=JSON.parse(app.store.getItem('ses-metricas-view-state-v1'));assert.equal(saved.pages.hours.filters.from,'2026-09-01');assert.equal(saved.pages.dashboard.filters.project,'SIPES');vm.runInContext("compareSprints=['A'];evolutionProjects=['B'];applyView({});rememberView()",app.context);assert.equal(vm.runInContext('compareSprints',app.context),null);assert.equal(vm.runInContext('evolutionProjects',app.context),null);});
test('evolução mantém SPs do mesmo card em cada sprint, reconciliando com o comparativo',()=>{const base=data.load(),a='SPRINT-31 31/08/2026 a 11/09/2026 (GSAS)',b='SPRINT-32 14/09/2026 a 25/09/2026 (GSAS)',sample={...base,items:[{...base.items[0],id:1,type:'História',project:'A',sprint:a,start:'2026-08-31',end:'2026-09-11',points:3},{...base.items[0],id:1,type:'História',project:'A',sprint:b,start:'2026-09-14',end:'2026-09-25',points:5}],hours:[],cycle:[],lead:[],rework:[],throughput:[],aging:[]};const r=query(sample,data,new URLSearchParams({view:'evolution'}));assert.deepEqual(r.evolution[0].values,[3,5]);assert.deepEqual(r.comparisons.map(x=>x.totalPoints),[3,5]);});
test('vínculo manual de OS com sprint removida não cria uma sprint inexistente',()=>{const context=vm.createContext({window:{}});vm.runInContext(fs.readFileSync('public/preferences.js','utf8'),context);const base=data.load(),order=base.items.find(x=>x.type==='Ordem de Serviço'),p={projects:null,owners:null,osLinks:{[order.id]:'SPRINT REMOVIDA'}};assert.ok(!context.window.MetricsPreferences.scope(base,p).items.some(x=>x.sprint==='SPRINT REMOVIDA'));});
