const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{Readable}=require('node:stream');const engine=require('../lib/data.cjs'),handler=require('../api/index.js');process.env.DASHBOARD_PASSWORD='local-test-password-only';process.env.SESSION_SECRET='local-test-session-key-32-characters-only';
async function request(action,params={},options={}){const req=Readable.from(options.body?[Buffer.from(JSON.stringify(options.body))]:[]);req.url='/api/index?'+new URLSearchParams({action,...params});req.method=options.method||'GET';req.headers={host:'localhost',...(options.cookie?{cookie:options.cookie}:{}),...options.headers};const headers={};let output;const res={statusCode:200,setHeader(k,v){headers[k.toLowerCase()]=v},end(v){output=v}};await handler(req,res);return {status:res.statusCode,headers,raw:output,body:headers['content-type']?.startsWith('application/json')?JSON.parse(output):output}}
async function login(){const r=await request('login',{}, {method:'POST',body:{password:process.env.DASHBOARD_PASSWORD}});assert.equal(r.status,200);return r.headers['set-cookie'].split(';')[0]}
test('base real: registros, apontamentos e OS sem pivôs ou linhas vazias',()=>{const d=engine.load();assert.equal(d.items.length,5136);assert.equal(d.hours.length,14146);assert.equal(d.items.filter(x=>x.type==='Ordem de Serviço').length,459);assert.equal(d.aging.length,260);assert.equal(d.metadata.lastHoursDate,'2026-09-25');assert.equal(new Set(d.items.map(x=>x.id)).size,5125);assert.equal(d.metadata.counts.duplicateRows,11)});
test('planejamento não informado permanece separado de não planejado',()=>{const s=engine.summary(engine.load()).stats;assert.equal(s.cards,4666);assert.equal(s.plannedCards+s.unplannedCards+s.unknownPlan,s.cards);assert.ok(s.unknownPlan>0);assert.ok(s.plannedPoints>=s.donePlannedPoints);assert.ok(s.delivery>=0&&s.delivery<=100);assert.equal(s.completed,engine.load().items.filter(x=>x.type!=='Ordem de Serviço'&&engine.done(x)).length)});
test('datas da sprint e filtros combinados preservam projeto, squad e intervalo',()=>{assert.deepEqual(engine.sprintDates('SPRINT-31 31/08/2026 a 11/09/2026 (GSAS)'),{start:'2026-08-31',end:'2026-09-11'});const s=engine.summary(engine.load(),{project:'SIGAPE',squad:'GSAS-SQUAD1',from:'2026-09-01',to:'2026-09-30'});assert.ok(s.items.length>0);assert.ok(s.items.every(x=>x.project==='SIGAPE'&&x.squad==='GSAS-SQUAD1'&&x.start<='2026-09-30'&&x.end>='2026-09-01'));assert.equal(s.stats.cycle,null);assert.equal(s.stats.rework,null);assert.ok(s.hours.every(x=>x.project==='SIGAPE'&&x.date>='2026-09-01'&&x.date<='2026-09-30'))});
test('métricas agregadas: média ponderada e filtros de granularidade',()=>{const d=engine.load(),s=engine.summary(d,{squad:'GSAS-SQUAD1'}),a=d.cycle.filter(x=>x.squad==='GSAS-SQUAD1'&&x.value!==null&&x.count>0),expected=a.reduce((v,x)=>v+x.value*x.count,0)/a.reduce((v,x)=>v+x.count,0);assert.equal(s.stats.cycle,expected);assert.equal(engine.summary(d,{status:'11-Concluído'}).stats.hours,null);assert.equal(engine.summary(d,{project:'SIGAPE'}).stats.lead,null)});
test('horas, faixas de aging e retrabalho reconciliam com os registros',()=>{const d=engine.load(),s=engine.summary(d);assert.equal(s.stats.hours,d.hours.reduce((v,x)=>v+(x.hours||0),0));assert.equal(s.stats.rework,d.rework.reduce((v,x)=>v+(x.value||0),0));assert.equal(s.charts.activityHours.reduce((v,x)=>v+x.value,0).toFixed(5),s.stats.hours.toFixed(5));assert.equal(s.charts.aging.reduce((v,x)=>v+x.value,0),s.stats.agingCards)});
test('variações de escrita das datas não excluem sprints válidas',()=>{assert.equal(engine.sprintDates('SPRINT-18 02/03/2026 A 13/03/2026 (GSAS)').start,'2026-03-02');assert.equal(engine.sprintDates('SPRINT-01 17/08/2026 à 28/08/2026 (PMR)').end,'2026-08-28')});
test('paginação tem limites e não altera totais',()=>{let p=engine.paginate(engine.load().items,200);assert.equal(p.page,p.pages);assert.ok(p.rows.length<=50);assert.equal(p.total,5136);assert.equal(engine.paginate([],1).pages,1)});
test('dados são bloqueados sem sessão e login define cookie HttpOnly',async()=>{assert.equal((await request('dashboard')).status,401);const r=await request('login',{}, {method:'POST',body:{password:process.env.DASHBOARD_PASSWORD}});assert.match(r.headers['set-cookie'],/HttpOnly/);assert.match(r.headers['set-cookie'],/SameSite=Strict/);assert.equal((await request('session',{}, {cookie:r.headers['set-cookie'].split(';')[0]})).body.authenticated,true)});
test('cookie alterado é rejeitado; configuração ausente bloqueia dados',async()=>{const c=await login();assert.equal((await request('dashboard',{}, {cookie:c+'x'})).status,401);const previous=process.env.SESSION_SECRET;delete process.env.SESSION_SECRET;assert.equal((await request('dashboard',{}, {cookie:c})).status,401);process.env.SESSION_SECRET=previous});
test('todas as sete telas consultam dados reais pela API',async()=>{const c=await login();for(const view of ['dashboard','sprint','compare','evolution','effort','hours','os']){const r=await request('dashboard',{view},{cookie:c});assert.equal(r.status,200,view);assert.equal(r.body.metadata.counts.items,5136);assert.ok(r.body.items.rows.length<=50);if(view==='os')assert.equal(r.body.items.total,459);if(view==='evolution')assert.ok(r.body.evolution.length>0)}});
test('detalhes, lançamentos, CSV e estado vazio',async()=>{const c=await login(),id=engine.load().items[0].id;assert.equal((await request('item',{id},{cookie:c})).body.item.id,id);assert.equal((await request('item',{id:'-1'},{cookie:c})).status,404);assert.equal((await request('logs',{project:'SIGAPE'},{cookie:c})).status,200);const empty=await request('dashboard',{project:'Não existe'},{cookie:c});assert.equal(empty.body.stats.cards,0);const exportFile=await request('export',{view:'hours',project:'SIGAPE'},{cookie:c});assert.equal(exportFile.status,200);assert.match(exportFile.headers['content-type'],/text\/csv/);assert.ok(handler.csv([{title:'=HYPERLINK("x")'}],['title']).includes("'=HYPERLINK"))});
test('Make permanece desativado e não finge persistir atualizações',async()=>{assert.equal((await request('import',{}, {method:'POST'})).status,503);assert.equal((await request('import')).status,405)});
test('artefato Vercel separa arquivos públicos da base privada',()=>{const root=path.resolve(__dirname,'..','.vercel/output');assert.ok(fs.existsSync(path.join(root,'functions/api/index.func/data/snapshot.json.gz')));assert.ok(!fs.existsSync(path.join(root,'static/data')));assert.ok(fs.existsSync(path.join(root,'static/index.html')));assert.equal(JSON.parse(fs.readFileSync(path.join(root,'config.json'))).version,3);assert.equal(JSON.parse(fs.readFileSync(path.join(root,'functions/api/index.func/.vc-config.json'))).runtime,'nodejs22.x')});
