const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const engine=require('../lib/data.cjs');
test('scripts juntos inicializam o painel e renderizam as sete telas sem conflito global',async()=>{const root=path.resolve(__dirname,'../.vercel/output/static'),nodes=new Map(),listeners={};const node=selector=>{if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',hidden:false,addEventListener(){}});return nodes.get(selector)};const context=vm.createContext({URLSearchParams,Intl,Date,Set,Map,Blob,URL,location:{hash:''},document:{querySelector:node,addEventListener(){}},fetch:async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(root,'data/snapshot.json')))}),setTimeout(){},clearTimeout(){},setInterval(){}});context.localStorage={getItem:()=>JSON.stringify({demo:false})};context.window=context;context.addEventListener=(name,fn)=>listeners[name]=fn;for(const file of ['engine.js','query.js','preferences.js','view-state.js','app.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file});await new Promise(resolve=>setImmediate(resolve));assert.equal(node('#error').textContent,'');assert.equal(node('#side-source').textContent,'5.917 registros na base');for(const view of ['sprint','compare','evolution','effort','hours','os','dashboard']){context.location.hash='#'+view;listeners.hashchange();await new Promise(resolve=>setImmediate(resolve));assert.equal(node('#error').textContent,'',view);assert.ok(node('#content').innerHTML.length>200,view);assert.ok(!node('#content').innerHTML.includes('A consulta não foi concluída'),view)}});
test('site estático executa todas as consultas no navegador e exporta CSV',()=>{const root=path.resolve(__dirname,'../.vercel/output'),context=vm.createContext({window:{},URLSearchParams});for(const file of ['engine.js','query.js'])vm.runInContext(fs.readFileSync(path.join(root,'static',file),'utf8'),context);const raw=JSON.parse(fs.readFileSync(path.join(root,'static/data/snapshot.json'))),d=context.window.MetricsData.normalize(raw),query=q=>context.window.MetricsQuery.query(d,context.window.MetricsData,new URLSearchParams(q));for(const view of ['dashboard','sprint','compare','evolution','effort','hours','os']){const r=query({action:'dashboard',view});assert.equal(r.stats.cards,5387);assert.ok(r.items.rows.length<=50);if(view==='os')assert.equal(r.items.total,475)}assert.equal(query({action:'item',id:d.items[0].id}).item.id,d.items[0].id);assert.equal(query({action:'logs'}).total,14291);assert.equal(query({action:'dashboard',project:'Não existe'}).stats.cards,0);assert.match(query({action:'export',view:'hours'}),/owner/);assert.ok(!fs.existsSync(path.join(root,'functions')));assert.ok(!fs.readFileSync(path.join(root,'static/app.js'),'utf8').includes('/api/index'));assert.ok(!fs.readFileSync(path.join(root,'static/index.html'),'utf8').includes('id="login"'));});
test('base real: registros, apontamentos e OS sem pivôs ou linhas vazias',()=>{const d=engine.load();assert.equal(d.items.length,5917);assert.equal(d.hours.length,14291);assert.equal(d.items.filter(x=>x.type==='Ordem de Serviço').length,475);assert.equal(d.aging.length,266);assert.equal(d.metadata.lastHoursDate,'2026-09-29');assert.equal(new Set(d.items.map(x=>x.id)).size,5862);assert.equal(d.metadata.counts.duplicateRows,55)});
test('planejamento não informado permanece separado de não planejado',()=>{const s=engine.summary(engine.load()).stats;assert.equal(s.cards,5387);assert.equal(s.plannedCards+s.unplannedCards+s.unknownPlan,s.cards);assert.ok(s.unknownPlan>0);assert.ok(s.plannedPoints>=s.donePlannedPoints);assert.ok(s.delivery>=0&&s.delivery<=100);assert.equal(s.completed,[...new Map([...engine.load().items].sort((a,b)=>(a.start||'').localeCompare(b.start||'')).map(x=>[x.id,x])).values()].filter(x=>x.type!=='Ordem de Serviço'&&engine.done(x)).length)});
test('datas da sprint e filtros combinados preservam projeto, squad e intervalo',()=>{assert.deepEqual(engine.sprintDates('SPRINT-31 31/08/2026 a 11/09/2026 (GSAS)'),{start:'2026-08-31',end:'2026-09-11'});const s=engine.summary(engine.load(),{project:'SIGAPE',squad:'GSAS-SQUAD1',from:'2026-09-01',to:'2026-09-30'});assert.ok(s.items.length>0);assert.ok(s.items.every(x=>x.project==='SIGAPE'&&x.squad==='GSAS-SQUAD1'&&x.start<='2026-09-30'&&x.end>='2026-09-01'));assert.equal(s.stats.cycle,null);assert.equal(s.stats.rework,null);assert.ok(s.hours.every(x=>x.project==='SIGAPE'&&x.date>='2026-09-01'&&x.date<='2026-09-30'))});
test('métricas agregadas: média ponderada e filtros de granularidade',()=>{const d=engine.load(),s=engine.summary(d,{squad:'GSAS-SQUAD1'}),a=d.cycle.filter(x=>x.squad==='GSAS-SQUAD1'&&x.value!==null&&x.count>0),expected=a.reduce((v,x)=>v+x.value*x.count,0)/a.reduce((v,x)=>v+x.count,0);assert.equal(s.stats.cycle,expected);assert.equal(engine.summary(d,{status:'11-Concluído'}).stats.hours,null);assert.equal(engine.summary(d,{project:'SIGAPE'}).stats.lead,null)});
test('horas, faixas de aging e retrabalho reconciliam com os registros',()=>{const d=engine.load(),s=engine.summary(d);assert.equal(s.stats.hours,d.hours.reduce((v,x)=>v+(x.hours||0),0));assert.equal(s.stats.rework,d.rework.reduce((v,x)=>v+(x.value||0),0));assert.equal(s.charts.activityHours.reduce((v,x)=>v+x.value,0).toFixed(5),s.stats.hours.toFixed(5));assert.equal(s.charts.aging.reduce((v,x)=>v+x.value,0),s.stats.agingCards)});
test('variações de escrita das datas não excluem sprints válidas',()=>{assert.equal(engine.sprintDates('SPRINT-18 02/03/2026 A 13/03/2026 (GSAS)').start,'2026-03-02');assert.equal(engine.sprintDates('SPRINT-01 17/08/2026 à 28/08/2026 (PMR)').end,'2026-08-28')});
test('paginação tem limites e não altera totais',()=>{let p=engine.paginate(engine.load().items,200);assert.equal(p.page,p.pages);assert.ok(p.rows.length<=50);assert.equal(p.total,5917);assert.equal(engine.paginate([],1).pages,1)});

test('preferências persistem seleções, filtram métricas e respeitam seleção vazia',()=>{const context=vm.createContext({window:{}});vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../public/preferences.js'),'utf8'),context);const p=context.window.MetricsPreferences,store=new Map(),storage={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},d=engine.load(),owner=d.hours.find(x=>x.project==='SIPES'&&d.items.some(i=>i.project==='SIPES'&&i.owner===x.owner)).owner;p.save(storage,{projects:['SIPES'],owners:[owner]});const selected=p.scope(d,p.read(storage));assert.ok(selected.items.length>0);assert.ok(selected.items.every(x=>x.project==='SIPES'));assert.ok(selected.hours.every(x=>x.project==='SIPES'&&x.owner===owner));const stats=engine.summary(selected,{projectScope:true}).stats;assert.equal(stats.totalPoints,engine.summary(selected).stats.totalPoints);assert.equal(stats.cycle,null);assert.equal(stats.rework,null);assert.equal(p.scope(d,{projects:[],owners:null}).items.length,0);assert.equal(p.scope(d,{projects:null,owners:[]}).hours.length,0);p.save(storage,{projects:null,owners:null});assert.equal(p.scope(d,p.read(storage)).items.length,d.items.length)});

test('painel escolhe próxima sprint publicada e preserva SP ausentes',()=>{const {query}=require('../lib/query.cjs'),d=engine.load(),run=(base,extra={})=>query(base,engine,new URLSearchParams({view:'sprint-panel',...extra}));const first=run(d);assert.ok(first.sprintPanel.selected);const sprint='SPRINT-99 01/01/2027 a 14/01/2027 (GSAS)',next={...d,items:[...d.items,{...d.items[0],id:999999,sprint,start:'2027-01-01',end:'2027-01-14',type:'História',points:null}]};const updated=run(next);assert.equal(updated.sprintPanel.selected,sprint);assert.equal(updated.sprintPanel.metrics.total,null);assert.equal(updated.sprintPanel.metrics.missing,1);assert.equal(run(next,{sprint:first.sprintPanel.selected}).sprintPanel.selected,first.sprintPanel.selected);});

test('horas esperadas contam segunda a sexta e colaboradores sem lançamento',()=>{const {weekdayCount,query}=require('../lib/query.cjs');assert.equal(weekdayCount('2026-09-01','2026-09-30'),22);assert.equal(weekdayCount('2026-09-26','2026-09-27'),0);assert.equal(weekdayCount('2026-09-25','2026-09-28'),2);const d=engine.load(),owner=d.hours[0].owner,r=query(d,engine,new URLSearchParams({view:'hours',owner,from:'2027-01-04',to:'2027-01-08'}));assert.equal(r.capacity.days,5);assert.equal(r.owners.length,1);assert.equal(r.owners[0].expected,40);assert.equal(r.owners[0].value,0);assert.equal(r.stats.hoursDifference,-40);});

test('multiseleção cruza status e tipos, e percentuais usam Pronto para Homologação',()=>{const {query}=require('../lib/query.cjs'),d=engine.load(),q=new URLSearchParams({view:'sprint'});q.append('status','10-Pronto para homologação');q.append('status','11-Concluído');q.append('type','História');q.append('type','Bug HML');const r=query(d,engine,q);assert.ok(r.items.total>0);assert.ok(r.items.rows.every(x=>['10-Pronto para homologação','11-Concluído'].includes(x.status)&&['História','Bug HML'].includes(x.type)));for(const p of r.projects)assert.equal(p.progress,p.ready/p.cards*100);});
test('sprints com intervalos sobrepostos não duplicam horas no total',()=>{const {query}=require('../lib/query.cjs'),d=engine.load(),q=new URLSearchParams({view:'effort'});const a='SPRINT-32 14/09/2026 a 25/09/2026 (GSAS)',b='SPRINT-01 14/09/2026 a 25/09/2026 (GSIS)';q.append('sprint',a);q.append('sprint',b);const r=query(d,engine,q),expected=d.hours.filter(x=>x.date>='2026-09-14'&&x.date<='2026-09-25').reduce((s,x)=>s+(x.hours||0),0);assert.equal(r.stats.hours,expected);assert.equal(r.effortComparisons.length,2);assert.equal(r.effortComparisons[0].hours,expected);});

test('base atual importa os responsaveis da coluna Nome',()=>{const d=engine.load();assert.equal(d.metadata.sourceName,'csass-metricas (1).xlsx');assert.ok(d.items.some(x=>x.owner));const r=require('../lib/query.cjs').query(d,engine,new URLSearchParams({view:'sprint'}));assert.ok(r.developers.length>0);});
test('navegadores novos e antigos passam a usar a planilha real',()=>{const context=vm.createContext({window:{}});vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../public/preferences.js'),'utf8'),context);const p=context.window.MetricsPreferences;let value=null;const storage={getItem:()=>value,setItem:(k,v)=>value=v};assert.equal(p.read(storage).demo,false);value=JSON.stringify({demo:true,projects:['Projeto Alfa'],owners:['Desenvolvedor A']});const migrated=p.read(storage);assert.equal(migrated.demo,false);assert.equal(migrated.projects,null);assert.equal(migrated.owners,null);p.save(storage,{demo:false,projects:['SIPES']});assert.deepEqual(Array.from(p.read(storage).projects),['SIPES']);});
