const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
let cached;
function load(){if(!cached){const raw=JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(__dirname,'../data/snapshot.json.gz'))));cached=normalize(raw);cached.metadata.counts.uniqueItems=new Set(cached.items.map(x=>x.id)).size;cached.metadata.counts.duplicateRows=cached.items.length-cached.metadata.counts.uniqueItems;}return cached}
const text=v=>v==null?'':String(v),num=v=>typeof v==='number'&&Number.isFinite(v)?v:null;
function sprintDates(s){const m=text(s).match(/(\d{2})\/(\d{2})\/(\d{4})\s+[aàá]\s+(\d{2})\/(\d{2})\/(\d{4})/i);return m?{start:`${m[3]}-${m[2]}-${m[1]}`,end:`${m[6]}-${m[5]}-${m[4]}`}:{start:null,end:null}}
function normalize(s){return {metadata:s.metadata,items:s.items.map(r=>({id:r[0],title:text(r[1]),status:text(r[2]),project:text(r[3]),sprint:text(r[4]),type:text(r[5]),points:num(r[6]),confidence:text(r[7]),planned:r[8]===1||r[8]==='1'?true:r[8]===0||r[8]==='0'?false:null,squad:text(r[9]),tribe:text(r[10]),team:text(r[11]),...sprintDates(r[4])})),hours:s.hours.map(r=>({id:r[0],project:text(r[1]),story:r[2],task:r[3],description:text(r[4]),date:text(r[5]).slice(0,10),owner:text(r[6]),activity:text(r[7]),team:text(r[8]),squad:text(r[9]),tribe:text(r[10]),hours:num(r[11])})),aging:s.aging.map(r=>({squad:text(r[0]),id:r[1],band:text(r[2])})),cycle:s.cycle.map(metric),lead:s.lead.map(metric),throughput:s.throughput.map(metric),rework:s.rework.map(metric)}}
function metric(r){return {squad:text(r[0]),sprint:text(r[1]),value:num(r[2]),count:num(r[3]),...sprintDates(r[1])}}
const done=x=>/conclu[ií]d|^entregue$/i.test(x.status),cancel=x=>/cancelad/i.test(x.status),bug=x=>/bug/i.test(x.type),spill=x=>/transbord/i.test(x.status),working=x=>/em desenvolvimento|em andamento|em an[aá]lise|em qualidade|em publica[cç][aã]o|ref\. t[eé]cnico|ref\. de neg[oó]cio/i.test(x.status);
const sum=(a,k)=>a.reduce((v,x)=>v+(typeof x[k]==='number'?x[k]:0),0),unique=a=>[...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
function rangeMatch(x,f){if(f.from&&(!x.end||x.end<f.from))return false;if(f.to&&(!x.start||x.start>f.to))return false;return true}
function itemMatch(x,f){return ['project','squad','team','status','type','sprint'].every(k=>!f[k]||x[k]===f[k])&&rangeMatch(x,f)}
function metricsMatch(x,f){return (!f.squad||x.squad===f.squad)&&(!f.team||x.squad.startsWith(f.team+'-'))&&(!f.sprint||x.sprint===f.sprint)&&rangeMatch(x,f)}
function logsMatch(x,f){if(f.status||f.type)return false;let period=f.sprint?sprintDates(f.sprint):{};if(f.sprint&&!period.start)return false;return ['project','squad','team','owner','activity'].every(k=>!f[k]||x[k]===f[k])&&(!f.from||x.date>=f.from)&&(!f.to||x.date<=f.to)&&(!period.start||x.date>=period.start&&x.date<=period.end)}
function group(a,key,value){const m=new Map();a.forEach(x=>{let k=x[key]||'Não informado';m.set(k,(m.get(k)||0)+(value?(x[value]??0):1))});return [...m].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)}
function options(d){const sprintSet=unique([...d.items.map(x=>x.sprint),...d.cycle.map(x=>x.sprint)]);return {projects:unique([...d.items.map(x=>x.project),...d.hours.map(x=>x.project)]),squads:unique([...d.items.map(x=>x.squad),...d.hours.map(x=>x.squad)]),teams:unique([...d.items.map(x=>x.team),...d.hours.map(x=>x.team)]),owners:unique(d.hours.map(x=>x.owner)),activities:unique(d.hours.map(x=>x.activity)),statuses:unique(d.items.map(x=>x.status)),types:unique(d.items.map(x=>x.type)),sprints:sprintSet.sort((a,b)=>(sprintDates(b).start||'').localeCompare(sprintDates(a).start||'')||a.localeCompare(b))}}
function weighted(a){const valid=a.filter(x=>x.value!==null&&x.count>0);const count=sum(valid,'count');return count?valid.reduce((v,x)=>v+x.value*x.count,0)/count:null}
function distinctItems(a){const m=new Map();for(const x of a)if(!m.has(x.id))m.set(x.id,x);return [...m.values()]}
function summary(d,f={}){const filtered=d.items.filter(x=>itemMatch(x,f)).sort((a,b)=>(b.start||'').localeCompare(a.start||'')),records=distinctItems(filtered),items=records.filter(x=>x.type!=='Ordem de Serviço'),hours=d.hours.filter(x=>logsMatch(x,f)),orders=records.filter(x=>x.type==='Ordem de Serviço'),ids=new Set(items.map(x=>x.id)),aging=d.aging.filter(x=>ids.has(x.id)),complete=items.filter(done),planned=items.filter(x=>x.planned===true),plannedDone=planned.filter(done),preciseMetrics=!f.projectScope&&!f.project&&!f.status&&!f.type&&!f.owner&&!f.activity,cycle=preciseMetrics?d.cycle.filter(x=>metricsMatch(x,f)):[],lead=preciseMetrics?d.lead.filter(x=>metricsMatch(x,f)):[],rework=preciseMetrics?d.rework.filter(x=>metricsMatch(x,f)):[],throughput=preciseMetrics?d.throughput.filter(x=>metricsMatch(x,f)):[],projectStats=unique(items.map(x=>x.project)).map(project=>{const a=items.filter(x=>x.project===project),closed=a.filter(done),cancelled=a.filter(cancel),opened=a.filter(x=>!done(x)&&!cancel(x));return {project,cards:a.length,done:closed.length,open:opened.length,cancelled:cancelled.length,points:sum(a,'points'),progress:a.length?closed.length/a.length*100:0,squads:unique(a.map(x=>x.squad)),status:opened.length?'Com itens abertos':closed.length?'Somente finalizados':'Somente cancelados'}});
const warnings=[];if(f.from||f.to)warnings.push('O período dos cards é definido pelas datas da sprint. Itens sem sprint datada ficam fora do recorte. Horas usam a data do apontamento.');if(f.status||f.type)warnings.push('Horas indisponíveis neste recorte: os apontamentos não possuem status ou tipo de card.');if(!preciseMetrics)warnings.push('Cycle time, lead time, vazão e retrabalho indisponíveis neste recorte: a fonte dessas métricas está agregada por squad e sprint.');warnings.push('A base não informa responsável dos cards, prioridade de projeto, dias exatos de aging ou capacidade de horas esperadas.');
return {items,hours,orders,projectStats,stats:{cards:items.length,completed:complete.length,inProgress:items.filter(working).length,plannedCards:planned.length,unplannedCards:items.filter(x=>x.planned===false).length,unknownPlan:items.filter(x=>x.planned===null).length,plannedPoints:sum(planned,'points'),donePlannedPoints:sum(plannedDone,'points'),totalPoints:sum(items,'points'),donePoints:sum(complete,'points'),delivery:sum(planned,'points')?sum(plannedDone,'points')/sum(planned,'points')*100:null,bugs:items.filter(bug).length,spill:items.filter(spill).length,rework:preciseMetrics?sum(rework,'value'):null,throughput:preciseMetrics?sum(throughput,'value'):null,cycle:weighted(cycle),lead:weighted(lead),projects:projectStats.length,projectsOpen:projectStats.filter(x=>x.open).length,projectsDone:projectStats.filter(x=>!x.open&&x.done).length,hours:f.status||f.type?null:sum(hours,'hours'),owners:unique(hours.map(x=>x.owner)).length,agingCards:aging.length,orders:orders.length},charts:{statuses:group(items,'status'),projects:group(items,'project','points'),squads:group(items,'squad','points'),projectHours:group(hours,'project','hours'),activityHours:group(hours,'activity','hours'),ownerHours:group(hours,'owner','hours'),aging:group(aging,'band'),projectSituations:group(projectStats,'status')},warnings}}
function sprintSummary(d,f){const s=summary(d,f),names=unique([...s.items.map(x=>x.sprint),...d.rework.filter(x=>metricsMatch(x,f)&&!f.project&&!f.status&&!f.type).map(x=>x.sprint)]).filter(Boolean);return names.map(sprint=>{let r=summary(d,{...f,sprint});return {sprint,...sprintDates(sprint),...r.stats}}).sort((a,b)=>(a.start||'').localeCompare(b.start||'')||a.sprint.localeCompare(b.sprint))}
function paginate(a,page=1,size=50){const total=a.length,pages=Math.max(1,Math.ceil(total/size)),current=Math.max(1,Math.min(pages,Number(page)||1));return {rows:a.slice((current-1)*size,current*size),page:current,pageSize:size,total,pages}}
function cardCategory(a,tab){return a.filter(x=>!tab||tab==='all'||tab==='planned'&&x.planned===true||tab==='unplanned'&&x.planned===false||tab==='bugs'&&bug(x)||tab==='spill'&&spill(x))}
function queryFilters(q){const f={};if(q.get('projectScope')==='1')f.projectScope=true;for(const k of ['project','squad','team','status','type','sprint','owner','activity','from','to'])if(q.get(k))f[k]=q.get(k);for(const k of ['from','to'])if(f[k]&&!/^\d{4}-\d{2}-\d{2}$/.test(f[k]))throw Error('Período inválido');if(f.from&&f.to&&f.from>f.to)throw Error('A data inicial deve ser anterior à final');return f}
module.exports={load,normalize,sprintDates,summary,sprintSummary,options,paginate,cardCategory,queryFilters,group,sum,done,bug,spill};
