function csv(a,keys){const value=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};return '\ufeff'+keys.map(value).join(';')+'\r\n'+a.map(r=>keys.map(k=>value(Array.isArray(r[k])?r[k].join(', '):r[k])).join(';')).join('\r\n')}
function query(dataset,data,q){const action=q.get("action")||"dashboard";if(q.get('view')==='sprint-panel'&&action==='dashboard')return sprintPanel(dataset,data,q);const d=dataset,f=data.queryFilters(q),s=data.summary(d,f),search=(q.get('search')||'').toLocaleLowerCase('pt-BR');const match=x=>!search||JSON.stringify(x).toLocaleLowerCase('pt-BR').includes(search);
if(action==='item'){const entries=d.items.filter(x=>String(x.id)===q.get('id')).sort((a,b)=>(b.start||'').localeCompare(a.start||''));const item=q.get('sprint')?entries.find(x=>x.sprint===q.get('sprint')):entries[0];if(!item)throw new Error('Item não encontrado');const aging=d.aging.find(x=>x.id===item.id);return ({item,sourceSprints:[...new Set(entries.map(x=>x.sprint).filter(Boolean))],aging:aging?.band??null,note:item.type==='Ordem de Serviço'?'A planilha não fornece vínculo OS → história, justificativa ou controle de e-mail.':'A planilha não fornece responsável do card, justificativa ou datas individuais de transição.'})}
if(action==='export'){const view=q.get('view'),rows=view==='hours'?s.hours:view==='os'?s.orders:view==='projects'?s.projectStats:s.items,keys=view==='hours'?['id','project','date','owner','activity','squad','hours']:view==='projects'?['project','status','cards','done','open','points','progress']:['id','title','project','sprint','status','type','points','planned','squad','team'];return csv(rows.filter(match),keys)}
if(action==='logs')return (data.paginate(s.hours.filter(match),q.get('page')));
if(action==='dashboard'){const view=q.get('view')||'dashboard';const list=view==='os'?s.orders:data.cardCategory(s.items,q.get('tab'));let comparisons=[],evolution=[];if(['compare','evolution','dashboard'].includes(view)){comparisons=data.sprintSummary(d,f);if(view==='compare'){const selected=q.getAll('compareSprint');if(selected.length)comparisons=comparisons.filter(x=>selected.includes(x.sprint));else comparisons=comparisons.filter(x=>x.start).slice(-3)}if(view==='evolution'){comparisons=comparisons.filter(x=>x.start).slice(-10);const requested=q.getAll('evolutionProject');const selected=requested.length?requested:s.charts.projects.slice(0,3).map(x=>x.label);evolution=selected.slice(0,6).map(project=>({project,values:comparisons.map(c=>data.sum(s.items.filter(x=>x.project===project&&x.sprint===c.sprint),'points'))}))}}const capacity=view==='hours'?hoursCapacity(d,data,f,s.hours):null;const owners=capacity?capacity.owners:data.group(s.hours,'owner','hours');if(capacity){s.stats.owners=owners.length;s.stats.expectedHours=capacity.expected;s.stats.hoursDifference=s.stats.hours===null?null:s.stats.hours-capacity.expected;}const activities=data.group(s.hours,'activity','hours');return ({metadata:d.metadata,options:data.options(d),stats:s.stats,charts:s.charts,projects:s.projectStats,comparisons,evolution,owners,activities,capacity,items:data.paginate(list.filter(match),q.get('page')),warnings:s.warnings,filter:f})}
throw new Error('Consulta desconhecida')
}

function sprintPanel(d,data,q){
 const f=data.queryFilters(q),base={...f};delete base.sprint;
 const candidates=data.sprintSummary(d,base).filter(x=>x.start&&x.cards>0);
 const preferred=candidates.filter(x=>/\(GSAS\)$/i.test(x.sprint));const selected=f.sprint||(preferred.length?preferred:candidates).at(-1)?.sprint||'';
 const current=data.summary(d,{...f,sprint:selected});
 const family=selected.match(/\(([^)]+)\)$/)?.[1];const sequence=candidates.filter(x=>!family||x.sprint.endsWith('('+family+')'));const index=sequence.findIndex(x=>x.sprint===selected),previous=index>0?data.summary(d,{...base,sprint:sequence[index-1].sprint}):null;
 const points=items=>!items.length?0:items.some(x=>typeof x.points==='number')?data.sum(items,'points'):null;
 const metrics=items=>({total:points(items),planned:points(items.filter(x=>x.planned===true)),unplanned:points(items.filter(x=>x.planned===false)),done:points(items.filter(data.done)),spill:points(items.filter(data.spill)),bugs:items.filter(data.bug).length,bugDev:items.filter(x=>/^Bug DEV$/i.test(x.type)).length,bugHml:items.filter(x=>/^Bug HML$/i.test(x.type)).length,bugProd:items.filter(x=>/^Bug PRD$/i.test(x.type)).length,missing:items.filter(x=>x.points===null).length,cards:items.length});
 return {metadata:d.metadata,options:data.options(d),filter:{...f,sprint:selected},stats:current.stats,charts:current.charts,warnings:current.warnings,items:data.paginate(data.cardCategory(current.items,q.get('tab')).filter(x=>!(q.get('search')||'')||JSON.stringify(x).toLocaleLowerCase('pt-BR').includes(q.get('search').toLocaleLowerCase('pt-BR'))),q.get('page')),sprintPanel:{selected,previous:previous?sequence[index-1].sprint:null,metrics:metrics(current.items),previousMetrics:previous?metrics(previous.items):null,projects:current.projectStats.map(x=>({project:x.project,...metrics(current.items.filter(i=>i.project===x.project))})),owners:data.group(current.hours,'owner','hours'),available:candidates.length}};
}

function weekdayCount(from,to){if(!from||!to||from>to)return 0;const start=new Date(from+'T00:00:00Z'),end=new Date(to+'T00:00:00Z');if(!Number.isFinite(+start)||!Number.isFinite(+end))return 0;const days=Math.floor((end-start)/86400000)+1;let count=Math.floor(days/7)*5;for(let i=0;i<days%7;i++){const day=(start.getUTCDay()+i)%7;if(day!==0&&day!==6)count++;}return count;}
function hoursCapacity(d,data,f,hours){
 const dates=d.hours.map(x=>x.date).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)).sort();const sprint=f.sprint?data.sprintDates(f.sprint):{};
 let from=f.from||sprint.start||dates[0]||null,to=f.to||sprint.end||dates.at(-1)||null;
 if(sprint.start&&from<sprint.start)from=sprint.start;if(sprint.end&&to>sprint.end)to=sprint.end;
 const valid=!!from&&!!to&&(!f.sprint||!!sprint.start),days=valid?weekdayCount(from,to):0,expectedPerOwner=valid?days*8:null;
 const roster=d.hours.filter(x=>['project','squad','team','owner'].every(k=>!f[k]||x[k]===f[k]));
 const totals=new Map(data.group(hours,'owner','hours').map(x=>[x.label,x.value]));const owners=[...new Set(roster.map(x=>x.owner).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(label=>({label,value:totals.get(label)||0,expected:expectedPerOwner,difference:expectedPerOwner===null?null:(totals.get(label)||0)-expectedPerOwner}));
 return {from,to,days,expectedPerOwner,expected:expectedPerOwner===null?null:expectedPerOwner*owners.length,owners};
}
module.exports={query,csv,sprintPanel,weekdayCount,hoursCapacity};
