const crypto=require('node:crypto');const data=require('../lib/data.cjs');
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(body))}
function equal(a,b){return crypto.timingSafeEqual(crypto.createHash('sha256').update(String(a)).digest(),crypto.createHash('sha256').update(String(b)).digest())}
function configured(){return process.env.DASHBOARD_PASSWORD?.length>=12&&process.env.SESSION_SECRET?.length>=32}
function sign(s){return crypto.createHmac('sha256',process.env.SESSION_SECRET).update(s).digest('base64url')}
function authenticated(req){if(!configured())return false;try{const cookie=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('ses_session='))?.slice(12);if(!cookie)return false;const [payload,sig,...extra]=cookie.split('.');if(extra.length||!payload||!sig||!equal(sign(payload),sig))return false;const session=JSON.parse(Buffer.from(payload,'base64url').toString());return session.scope==='dashboard'&&typeof session.exp==='number'&&session.exp>Date.now()&&session.exp<Date.now()+9*3600000}catch{return false}}
function cookie(res,value,maxAge){res.setHeader('Set-Cookie',`ses_session=${value}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}${process.env.VERCEL?' ; Secure':''}`)}
async function body(req){if(req.body!==undefined)return typeof req.body==='string'?JSON.parse(req.body):req.body;let size=0,chunks=[];for await(const b of req){size+=b.length;if(size>4096)throw Error('Requisição excede o limite');chunks.push(b)}return JSON.parse(Buffer.concat(chunks).toString()||'{}')}
function method(req,res,allowed){if(req.method!==allowed){res.setHeader('Allow',allowed);json(res,405,{error:'Método não permitido'});return false}return true}
function csv(a,keys){const value=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};return '\ufeff'+keys.map(value).join(';')+'\r\n'+a.map(r=>keys.map(k=>value(Array.isArray(r[k])?r[k].join(', '):r[k])).join(';')).join('\r\n')}
async function handler(req,res){res.setHeader('Cache-Control','private, no-store, max-age=0');res.setHeader('X-Content-Type-Options','nosniff');const u=new URL(req.url,'http://localhost'),q=u.searchParams,action=q.get('action')||'dashboard';try{
if(action==='session'){if(!method(req,res,'GET'))return;return json(res,200,{authenticated:authenticated(req),configured:configured()})}
if(action==='login'){if(!method(req,res,'POST'))return;if(!configured())return json(res,503,{error:'Configure DASHBOARD_PASSWORD (12 caracteres ou mais) e SESSION_SECRET (32 caracteres ou mais) no painel da Vercel.'});const origin=req.headers.origin;if(origin&&new URL(origin).host!==req.headers.host)return json(res,403,{error:'Origem inválida'});let b=await body(req);if(typeof b.password!=='string'||!equal(b.password,process.env.DASHBOARD_PASSWORD)){await new Promise(r=>setTimeout(r,750));return json(res,401,{error:'Senha incorreta'})}const payload=Buffer.from(JSON.stringify({scope:'dashboard',exp:Date.now()+8*3600000,nonce:crypto.randomBytes(12).toString('hex')})).toString('base64url');cookie(res,payload+'.'+sign(payload),8*3600);return json(res,200,{ok:true})}
if(action==='logout'){if(!method(req,res,'POST'))return;cookie(res,'',0);return json(res,200,{ok:true})}
if(action==='import'){if(!method(req,res,'POST'))return;if(!process.env.IMPORT_SECRET)return json(res,503,{error:'Integração Make ainda não configurada'});if(!equal(req.headers.authorization||'','Bearer '+process.env.IMPORT_SECRET))return json(res,401,{error:'Chave da integração inválida'});return json(res,501,{error:'Recebimento automático desativado. A próxima etapa é conectar armazenamento privado e validar a importação antes de substituir a base.'})}
if(!authenticated(req))return json(res,401,{error:'Entre para consultar os dados'});if(!method(req,res,'GET'))return;const d=data.load(),f=data.queryFilters(q),s=data.summary(d,f),search=(q.get('search')||'').toLocaleLowerCase('pt-BR');const match=x=>!search||JSON.stringify(x).toLocaleLowerCase('pt-BR').includes(search);
if(action==='item'){const entries=d.items.filter(x=>String(x.id)===q.get('id')).sort((a,b)=>(b.start||'').localeCompare(a.start||''));const item=q.get('sprint')?entries.find(x=>x.sprint===q.get('sprint')):entries[0];if(!item)return json(res,404,{error:'Item não encontrado'});const aging=d.aging.find(x=>x.id===item.id);return json(res,200,{item,sourceSprints:[...new Set(entries.map(x=>x.sprint).filter(Boolean))],aging:aging?.band??null,note:item.type==='Ordem de Serviço'?'A planilha não fornece vínculo OS → história, justificativa ou controle de e-mail.':'A planilha não fornece responsável do card, justificativa ou datas individuais de transição.'})}
if(action==='export'){const view=q.get('view'),rows=view==='hours'?s.hours:view==='os'?s.orders:view==='projects'?s.projectStats:s.items,keys=view==='hours'?['id','project','date','owner','activity','squad','hours']:view==='projects'?['project','status','cards','done','open','points','progress']:['id','title','project','sprint','status','type','points','planned','squad','team'];res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="metricas-${['hours','os','projects'].includes(view)?view:'cards'}.csv"`);return res.end(csv(rows.filter(match),keys))}
if(action==='logs')return json(res,200,data.paginate(s.hours.filter(match),q.get('page')));
if(action==='dashboard'){const view=q.get('view')||'dashboard';const list=view==='os'?s.orders:data.cardCategory(s.items,q.get('tab'));let comparisons=[],evolution=[];if(['compare','evolution','dashboard'].includes(view)){comparisons=data.sprintSummary(d,f);if(view==='compare'){const selected=q.getAll('compareSprint');if(selected.length)comparisons=comparisons.filter(x=>selected.includes(x.sprint));else comparisons=comparisons.filter(x=>x.start).slice(-3)}if(view==='evolution'){comparisons=comparisons.filter(x=>x.start).slice(-10);const requested=q.getAll('evolutionProject');const selected=requested.length?requested:s.charts.projects.slice(0,3).map(x=>x.label);evolution=selected.slice(0,6).map(project=>({project,values:comparisons.map(c=>data.sum(s.items.filter(x=>x.project===project&&x.sprint===c.sprint),'points'))}))}}const owners=data.group(s.hours,'owner','hours');const activities=data.group(s.hours,'activity','hours');return json(res,200,{metadata:d.metadata,options:data.options(d),stats:s.stats,charts:s.charts,projects:s.projectStats,comparisons,evolution,owners,activities,items:data.paginate(list.filter(match),q.get('page')),warnings:s.warnings,filter:f})}
return json(res,404,{error:'Rota não encontrada'})
}catch(e){console.error('API:',e.message);return json(res,400,{error:'Não foi possível processar a consulta. Confira os filtros ou tente novamente.'})}}
module.exports=handler;module.exports.authenticated=authenticated;module.exports.csv=csv;
